### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by ThiraTheNerd** [coder-mylles/instaclone#1]
![Screenshot from 2021-07-15 15-09-50](https://user-images.githubusercontent.com/51013354/125786038-154354b6-b6e4-4a62-9479-6e594ecbac10.png)

**Comment by coder-mylles** [comment]
The login page is okay no issues that I can see

**Comment by ThiraTheNerd** [comment]
I only did that so that I can get to display the images on the Readme. The
issue exists in accessing the admin page it redirects to the login page

**Comment by coder-mylles** [comment]
ooh okay

**Comment by ThiraTheNerd** [comment]
I liked your project too. Good job👍

**Comment by coder-mylles** [comment]
Thanks a lot, I appreciate 💯
